name: CI

on:
  push:

  schedule:
  - cron: "0 0 * * 0"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Docker pull base image
      run: docker pull perl:5.30.0

    - name: Run test in t/
      run: docker run --rm --volume=`pwd`/lib/:/app/lib/ --volume=`pwd`/t/:/app/t/ perl:5.30.0 sh -c 'cd /app/; prove -l t/'
